### ISSUE TITLE
Received '501 Not Implemented'

### ISSUE THREAD

**Issue by lweijl** [asyd/jscep-cli-jdk6#19]
Firing the command ```java -jar jscep-cli-jdk6/target/jscepcli-1.0-SNAPSHOT-exe.jar --ca-identifier CA_Name_From_EJBCA --challenge my_challenge --dn "CN=lennarttest" --key-file ./test.key --url http://10.33.0.10:8080/ejbca/publicweb/apply/scep/pkiclient.exe -v --csr-file ./test.csr``` seems to generate a key, csr and fetches the CA certificate. After that a 501 Not Implemented is returned from EJBCA. Am I missing something at the EJBCA end or am I missing something else? Kind of in the dark right now.. The fetched CA certificate is the correct one, so at least part of it is working for me.

```
276 [main] DEBUG org.jscep.client.inspect.AbstractCertStoreInspector  - Using [issuer=CN= CA_Name_From_EJBCA; serial=6435838760199311421] for issuing entity
276 [main] DEBUG org.jscep.client.Client  - Requesting certificate verification.
277 [main] DEBUG org.jscep.client.Client  - Certificate verification passed.
277 [main] DEBUG org.jscep.client.Client  - Verifying signature of RA certificate
277 [main] DEBUG org.jscep.client.Client  - RA and CA are identical
277 [main] DEBUG org.jscep.client.Client  - Verifying signature of RA certificate
278 [main] DEBUG org.jscep.client.Client  - RA and CA are identical
306 [main] DEBUG org.jscep.client.Client  - Determining capabilities of SCEP server
307 [main] DEBUG org.jscep.transport.UrlConnectionGetTransport  - Sending GetCACaps(CA_Name_From_EJBCA) to http://10.33.0.10:8080/ejbca/publicweb/apply/scep/pkiclient.exe?operation=GetCACaps&message=CA_Name_From_EJBCA
326 [main] DEBUG org.jscep.transport.UrlConnectionGetTransport  - Received '200 OK' when sending GetCACaps(CA_Name_From_EJBCA) to http://10.33.0.10:8080/ejbca/publicweb/apply/scep/pkiclient.exe?operation=GetCACaps&message=CA_Name_From_EJBCA
326 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - CA capabilities:
326 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] Certificate Rollover
327 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] HTTP POST
327 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] Certificate Renewal
327 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] SHA-512 Message Digest
328 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] SHA-256 Message Digest
328 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] SHA-1 Message Digest
328 [main] DEBUG org.jscep.transport.response.GetCaCapsResponseHandler  - [?] Triple DES Encryption
330 [main] INFO org.jscep.client.Client  - SHA-1 PKCS#10 Fingerprint: [bd33a2cd6fe53e8a41aba8e769a22e46f7646ca1]
330 [main] DEBUG org.jscep.message.PkiMessageEncoder  - Encoding pkiMessage
353 [main] DEBUG org.jscep.message.PkiMessageEncoder  - Encoding message: org.jscep.message.PkcsReq@365d15c6[transId=161a13f4c487e4d81f8a59274bb760e0fe197378,messageType=PKCS_REQ,senderNonce=Nonce [0d70e1ff665f2da4c53329a8492cf5a0],messageData=org.bouncycastle.pkcs.PKCS10CertificationRequest@3fa7bd89]
354 [main] DEBUG org.jscep.message.PkcsPkiEnvelopeEncoder  - Encoding pkcsPkiEnvelope
362 [main] DEBUG org.jscep.message.PkcsPkiEnvelopeEncoder  - Encrypting pkcsPkiEnvelope using key belonging to [issuer=CN=CA_Name_From_EJBCA; serial=6435838760199311421]
403 [main] DEBUG org.jscep.message.PkcsPkiEnvelopeEncoder  - Finished encoding pkcsPkiEnvelope
405 [main] DEBUG org.jscep.message.PkiMessageEncoder  - Signing pkiMessage using key belonging to [issuer=CN=lennarttest; serial=1]
425 [main] DEBUG org.jscep.message.PkiMessageEncoder  - Signing org.bouncycastle.cms.CMSProcessableByteArray@5157c61e content
453 [main] DEBUG org.jscep.message.PkiMessageEncoder  - Finished encoding pkiMessage
454 [main] DEBUG org.jscep.transaction.EnrollmentTransaction  - Sending org.bouncycastle.cms.CMSSignedData@72d8c235
578 [main] DEBUG org.jscep.transport.UrlConnectionPostTransport  - Received '501 Not Implemented' when sending org.bouncycastle.cms.CMSSignedData@72d8c235 to http://10.33.0.10:8080/ejbca/publicweb/apply/scep/pkiclient.exe?operation=PKIOperation
org.jscep.transaction.TransactionException: org.jscep.transport.TransportException: 501 Not Implemented
org.jscep.transaction.TransactionException: org.jscep.transport.TransportException: 501 Not Implemented
	at org.jscep.transaction.Transaction.send(Transaction.java:101)
	at org.jscep.transaction.EnrollmentTransaction.send(EnrollmentTransaction.java:116)
	at org.jscep.client.Client.send(Client.java:680)
	at org.jscep.client.Client.enrol(Client.java:635)
	at com.opencsi.jscepcli.App.scepCLI(App.java:121)
	at com.opencsi.jscepcli.App.main(App.java:285)
Caused by: org.jscep.transport.TransportException: 501 Not Implemented
	at org.jscep.transport.UrlConnectionPostTransport.sendRequest(UrlConnectionPostTransport.java:92)
	at org.jscep.transaction.Transaction.send(Transaction.java:99)
	... 5 more
```

**Comment by asyd** [comment]
Hi Lennart, 

have you check EJBCA logs?

**Comment by lweijl** [comment]
I did, could not find anything which was useful or related.
Since the project I'm on did not leave me with enough time to debug the problem, I fixed it by compiling a C client. Will look into it some more when I have time left.

Thanks for your time so far.
